"""add role to users

Revision ID: 376d1405cbca
Revises: f10a2b4aedce
Create Date: 2026-09-30 16:09:37.839885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "376d1405cbca"
down_revision: Union[str, Sequence[str], None] = "f10a2b4aedce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_table",
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            server_default="user",
        ),
    )
    op.alter_column("user_table", "role", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_table", "role")
    # ### end Alembic commands ###
