"""add user active status

Revision ID: 98b6acd67afc
Revises: 376d1405cbca
Create Date: 2026-09-30 17:54:18.985444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "98b6acd67afc"
down_revision: Union[str, Sequence[str], None] = "376d1405cbca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_table",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_table", "is_active")
    # ### end Alembic commands ###
