"""make email and phone unique

Revision ID: 9a31c49dfaaf
Revises: a9c2125e5aed
Create Date: 2026-09-26 17:27:24.492325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a31c49dfaaf'
down_revision: Union[str, Sequence[str], None] = 'a9c2125e5aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'avatar')
    # ### end Alembic commands ###
