"""add avatar in user model

Revision ID: a9c2125e5aed
Revises: 2a74adf12133
Create Date: 2026-09-26 16:41:44.032110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a9c2125e5aed"
down_revision: Union[str, Sequence[str], None] = "2a74adf12133"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_table", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user_table", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user_table", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(None, "user_table", ["email"])
    op.create_unique_constraint(None, "user_table", ["phone"])
    op.alter_column("user_tasks", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user_tasks", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user_tasks", "is_completed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("user_tasks", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_tasks", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "user_tasks", "is_completed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user_tasks", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user_tasks", "title", existing_type=sa.VARCHAR(), nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "user_table", type_="unique")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "user_table", type_="unique")
    op.alter_column("user_table", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user_table", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user_table", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
