"""replace is_completed with priority and status in taskModel

Revision ID: c3f5a1aae4dc
Revises: 9a31c49dfaaf
Create Date: 2026-09-28 11:24:39.663335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f5a1aae4dc'
down_revision: Union[str, Sequence[str], None] = '9a31c49dfaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('user_tasks', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_column('user_tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user_tasks', 'status')
    op.drop_column('user_tasks', 'priority')
    # ### end Alembic commands ###
