"""add assigned user and assigned task

Revision ID: d874020be098
Revises: c3f5a1aae4dc
Create Date: 2026-09-29 12:08:06.057117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d874020be098"
down_revision: Union[str, Sequence[str], None] = "c3f5a1aae4dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_assignments", sa.Column("task_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "task_assignments", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        "fk_task_assignments_user_id",
        "task_assignments",
        "user_table",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_task_assignments_task_id",
        "task_assignments",
        "user_tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_task_assignments_task_id", "task_assignments", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_task_assignments_user_id", "task_assignments", type_="foreignkey"
    )
    op.drop_column("task_assignments", "user_id")
    op.drop_column("task_assignments", "task_id")
    # ### end Alembic commands ###
